### ISSUE TITLE
JavaScript - script parsing error

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-ui-swing#61]
On Linux, Java 8. Opened the script editor and set lang to Javascript. Get a big stack trace.

Happens every time the script pane is updated.

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: org.mozilla.javascript.CompilerEnvirons.setIdeMode(Z)V
    at org.fife.rsta.ac.js.JavaScriptParser.createCompilerEnvironment(JavaScriptParser.java:115)
    at org.fife.rsta.ac.js.JavaScriptParser.parse(JavaScriptParser.java:250)
    at org.fife.ui.rsyntaxtextarea.ParserManager.actionPerformed(ParserManager.java:160)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
```

**Comment by ctrueden** [comment]
I think this is long fixed, resolved by an upgrade of RSyntaxTextArea and friends.
